on: push
name: Build Android & Web
jobs:
  build:
    name: Build Android & Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.20.0-7.2.pre'
          channel: 'beta'
      - name: Upgrades flutter
        run: flutter upgrade
      - name: Enable Web
        run: flutter config --enable-web
      - name: Install dependencies
        run: flutter packages get
      - name: Build Web
        run: flutter build web
      - name: Build Android Bundle
        run: flutter build appbundle --debug